//@version=5
indicator("Buz-ScalpTrend-New", shorttitle="Buz-ST-New", overlay=true, max_boxes_count = 500, max_lines_count = 500, max_labels_count = 500)
//Scalping indicator with multiple timeframe EMAs and dashboard
//v1 - Initial version

colorScheme = input.string("Dark", title = "Dark vs Light Mode", options = ["Dark", "Light"])
showTable = input(true, title="Show Dashboard")
showTrendFill = input(true, title="Show Trend Fill", group = "---Fills---")
showLabels = input(true, title="Show labels", group = "---Labels---")

//Current Timeframe EMAs
showEMA1 = input(true, title="Show EMA 13", group = "---Current TF EMAs---", inline = "1")
showEMA2 = input(true, title="Show EMA 23", group = "---Current TF EMAs---", inline = "1")
showEMA3 = input(true, title="Show EMA 35", group = "---Current TF EMAs---", inline = "2")
showEMA4 = input(true, title="Show EMA 200", group = "---Current TF EMAs---", inline = "2")

l1 = input.int(13, "EMA 1", group = "----- EMAs -----")
l2 = input.int(23, "EMA 2", group = "----- EMAs -----")
l3 = input.int(35, "EMA 3", group = "----- EMAs -----")
l4 = input.int(200, "EMA 4", group = "----- EMAs -----")

//HTF EMAs
show_15min13 = input(true, title="Show 15min EMA13", group = "---HTF EMAs---", inline = "3")
show_15min200 = input(true, title="Show 15min EMA200", group = "---HTF EMAs---", inline = "3")
show_1hr13 = input(true, title="Show 1hr EMA13", group = "---HTF EMAs---", inline = "4")
show_1hr200 = input(true, title="Show 1hr EMA200", group = "---HTF EMAs---", inline = "4")
show_4hr13 = input(true, title="Show 4hr EMA13", group = "---HTF EMAs---", inline = "5")
show_4hr200 = input(true, title="Show 4hr EMA200", group = "---HTF EMAs---", inline = "5")
show_Daily13 = input(true, title="Show Daily EMA13", group = "---HTF EMAs---", inline = "6")

//HTF Lines (optional plotting)
plot_15min13 = input(false, title="Plot 15min EMA13 Line", group = "---HTF Lines---", inline = "7")
plot_15min200 = input(false, title="Plot 15min EMA200 Line", group = "---HTF Lines---", inline = "7")
plot_1hr13 = input(false, title="Plot 1hr EMA13 Line", group = "---HTF Lines---", inline = "8")
plot_1hr200 = input(false, title="Plot 1hr EMA200 Line", group = "---HTF Lines---", inline = "8")
plot_4hr13 = input(false, title="Plot 4hr EMA13 Line", group = "---HTF Lines---", inline = "9")
plot_4hr200 = input(false, title="Plot 4hr EMA200 Line", group = "---HTF Lines---", inline = "9")
plot_Daily13 = input(false, title="Plot Daily EMA13 Line", group = "---HTF Lines---", inline = "10")

//HTF SMAs
show_1hr100 = input(true, title="Show 1hr SMA100", group = "---HTF SMAs---", inline = "11")
show_1hr300 = input(true, title="Show 1hr SMA300", group = "---HTF SMAs---", inline = "11")
plot_1hr100 = input(false, title="Plot 1hr SMA100 Line", group = "---HTF SMAs---", inline = "12")
plot_1hr300 = input(false, title="Plot 1hr SMA300 Line", group = "---HTF SMAs---", inline = "12")

l5 = input.int(100, "SMA 1", group = "----- SMAs -----")
l6 = input.int(300, "SMA 2", group = "----- SMAs -----")

// EMAs for current timeframe
ema1x = ta.ema(close, l1)
ema2x = ta.ema(close, l2)
ema3x = ta.ema(close, l3)
ema4x = ta.ema(close, l4)

//////////////////////////////////////////////////////////////////////////
//
//
//                     Plotting Current TF EMAs
//
//
//////////////////////////////////////////////////////////////////////////

// Plotting labels
var label Ema1Label = na
var label Ema2Label = na
var label Ema3Label = na
var label Ema4Label = na

//Colour Scheme
color labelcolour = colorScheme == "Dark" ? color.rgb(253, 253, 253, 40) : color.rgb(19, 10, 150, 40)
    
// Plotting Current TF EMAs
plot(showEMA1 ? ema1x : na, color=color.rgb(102, 182, 247), linewidth=2, title = "EMA 13")
plot(showEMA2 ? ema2x : na, color=color.rgb(83, 181, 247), linewidth=2, title = "EMA 23")
plot(showEMA3 ? ema3x : na, color=color.rgb(82, 85, 255), linewidth=2, title = "EMA 35")
plot(showEMA4 ? ema4x : na, color=color.rgb(6, 2, 253), linewidth=2, title = "EMA 200")

if barstate.islast
    // Delete previous labels
    if (not na(Ema1Label))
        label.delete(Ema1Label)
    if (not na(Ema2Label))
        label.delete(Ema2Label)
    if (not na(Ema3Label))
        label.delete(Ema3Label)
    if (not na(Ema4Label))
        label.delete(Ema4Label)
    ///
    if showEMA1 and showLabels
        Ema1Label := label.new(x=bar_index, y=ema1x, text= "EMA" + str.tostring(l1), xloc=xloc.bar_index, yloc=yloc.price, textcolor=labelcolour, style=label.style_label_left, color = color.rgb(1,1,1,100))
    if showEMA2 and showLabels
        Ema2Label := label.new(x=bar_index, y=ema2x, text="EMA" + str.tostring(l2), xloc=xloc.bar_index, yloc=yloc.price, textcolor=labelcolour, style=label.style_label_left, color = color.rgb(1,1,1,100))
    if showEMA3 and showLabels
        Ema3Label := label.new(x=bar_index, y=ema3x, text="EMA" + str.tostring(l3), xloc=xloc.bar_index, yloc=yloc.price, textcolor=labelcolour, style=label.style_label_left, color = color.rgb(1,1,1,100))
    if showEMA4 and showLabels
        Ema4Label := label.new(x=bar_index, y=ema4x, text="EMA" + str.tostring(l4), xloc=xloc.bar_index, yloc=yloc.price, textcolor=labelcolour, style=label.style_label_left, color = color.rgb(1,1,1,100))

// Check EMA order for trends
isDownTrend = ema1x < ema2x and ema2x < ema3x
isUpTrend = ema1x > ema2x and ema2x > ema3x

trendUpPrice = close > ema1x
trendDownPrice = close < ema1x

trendStatus = if isUpTrend and trendUpPrice
    "Uptrend"
else
    if isDownTrend and trendDownPrice
        "Downtrend"
    else
        "Sideways"

// Fill between EMA1 and EMA3 based on conditions
p5 = plot(ema1x, color=color.rgb(33, 149, 243, 100), title = "Fill Trend EMA 1")
p6 = plot(ema3x, color=color.rgb(76, 175, 79, 100), title = "Fill Trend EMA 2")
fill(p5, p6, color= isUpTrend and showTrendFill ? color.new(color.green, 60) : na, title="Bullish Zone")
fill(p5, p6, color= isDownTrend and showTrendFill ? color.new(color.red, 60) : na, title="Bearish Zone")

//////////////////////////////////////////////////////////////////////////
//
//
//                     HTF EMAs - 15min
//
//
//////////////////////////////////////////////////////////////////////////

ema15min13 = request.security(syminfo.tickerid, "15", ta.ema(close, l1))
plot(show_15min13 and plot_15min13 ? ema15min13 : na, "15min EMA13", color=color.rgb(51, 255, 0, 15), style=plot.style_cross, linewidth = 2)
var label M15_13Label = na
if barstate.islast
    if (not na(M15_13Label))
        label.delete(M15_13Label)
    if show_15min13 and showLabels
        M15_13Label := label.new(x=bar_index, y=ema15min13, text="<----15m EMA" + str.tostring(l1), xloc=xloc.bar_index, yloc=yloc.price, textcolor=labelcolour, style=label.style_label_left, color = color.rgb(1,1,1,100))

ema15min200 = request.security(syminfo.tickerid, "15", ta.ema(close, l4))
plot(show_15min200 and plot_15min200 ? ema15min200 : na, "15min EMA200", color=color.rgb(51, 255, 0, 15), style=plot.style_cross, linewidth = 2)
var label M15_200Label = na
if barstate.islast
    if (not na(M15_200Label))
        label.delete(M15_200Label)
    if show_15min200 and showLabels
        M15_200Label := label.new(x=bar_index, y=ema15min200, text="<----15m EMA" + str.tostring(l4), xloc=xloc.bar_index, yloc=yloc.price, textcolor=labelcolour, style=label.style_label_left, color = color.rgb(1,1,1,100))

//////////////////////////////////////////////////////////////////////////
//
//
//                     HTF EMAs - 1hr
//
//
//////////////////////////////////////////////////////////////////////////

ema1hr13 = request.security(syminfo.tickerid, "60", ta.ema(close, l1))
plot(show_1hr13 and plot_1hr13 ? ema1hr13 : na, "1hr EMA13", color=color.rgb(255, 195, 0, 15), style=plot.style_cross, linewidth = 2)
var label H1_13Label = na
if barstate.islast
    if (not na(H1_13Label))
        label.delete(H1_13Label)
    if show_1hr13 and showLabels
        H1_13Label := label.new(x=bar_index, y=ema1hr13, text="<----1hr EMA" + str.tostring(l1), xloc=xloc.bar_index, yloc=yloc.price, textcolor=labelcolour, style=label.style_label_left, color = color.rgb(1,1,1,100))

ema1hr200 = request.security(syminfo.tickerid, "60", ta.ema(close, l4))
plot(show_1hr200 and plot_1hr200 ? ema1hr200 : na, "1hr EMA200", color=color.rgb(255, 195, 0, 15), style=plot.style_cross, linewidth = 2)
var label H1_200Label = na
if barstate.islast
    if (not na(H1_200Label))
        label.delete(H1_200Label)
    if show_1hr200 and showLabels
        H1_200Label := label.new(x=bar_index, y=ema1hr200, text="<----1hr EMA" + str.tostring(l4), xloc=xloc.bar_index, yloc=yloc.price, textcolor=labelcolour, style=label.style_label_left, color = color.rgb(1,1,1,100))

//////////////////////////////////////////////////////////////////////////
//
//
//                     HTF EMAs - 4hr
//
//
//////////////////////////////////////////////////////////////////////////

ema4hr13 = request.security(syminfo.tickerid, "240", ta.ema(close, l1))
plot(show_4hr13 and plot_4hr13 ? ema4hr13 : na, "4hr EMA13", color=color.rgb(255, 128, 0, 15), style=plot.style_cross, linewidth = 2)
var label H4_13Label = na
if barstate.islast
    if (not na(H4_13Label))
        label.delete(H4_13Label)
    if show_4hr13 and showLabels
        H4_13Label := label.new(x=bar_index, y=ema4hr13, text="<----4hr EMA" + str.tostring(l1), xloc=xloc.bar_index, yloc=yloc.price, textcolor=labelcolour, style=label.style_label_left, color = color.rgb(1,1,1,100))

ema4hr200 = request.security(syminfo.tickerid, "240", ta.ema(close, l4))
plot(show_4hr200 and plot_4hr200 ? ema4hr200 : na, "4hr EMA200", color=color.rgb(255, 128, 0, 15), style=plot.style_cross, linewidth = 2)
var label H4_200Label = na
if barstate.islast
    if (not na(H4_200Label))
        label.delete(H4_200Label)
    if show_4hr200 and showLabels
        H4_200Label := label.new(x=bar_index, y=ema4hr200, text="<----4hr EMA" + str.tostring(l4), xloc=xloc.bar_index, yloc=yloc.price, textcolor=labelcolour, style=label.style_label_left, color = color.rgb(1,1,1,100))

//////////////////////////////////////////////////////////////////////////
//
//
//                     HTF EMAs - Daily
//
//
//////////////////////////////////////////////////////////////////////////

emaDaily13 = request.security(syminfo.tickerid, "1D", ta.ema(close, l1))
plot(show_Daily13 and plot_Daily13 ? emaDaily13 : na, "Daily EMA13", color=color.rgb(175, 19, 236, 15), style=plot.style_cross, linewidth = 2)
var label Daily_13Label = na
if barstate.islast
    if (not na(Daily_13Label))
        label.delete(Daily_13Label)
    if show_Daily13 and showLabels
        Daily_13Label := label.new(x=bar_index, y=emaDaily13, text="<----Daily EMA" + str.tostring(l1), xloc=xloc.bar_index, yloc=yloc.price, textcolor=labelcolour, style=label.style_label_left, color = color.rgb(1,1,1,100))

//////////////////////////////////////////////////////////////////////////
//
//
//                     HTF SMAs - 1hr
//
//
//////////////////////////////////////////////////////////////////////////

ma1hr100 = request.security(syminfo.tickerid, "60", ta.sma(close, l5))
plot(show_1hr100 and plot_1hr100 ? ma1hr100 : na, "1hr SMA100", color=#f73a89c0, linewidth = 2)
var label H1_100Label = na
if barstate.islast
    if (not na(H1_100Label))
        label.delete(H1_100Label)
    if show_1hr100 and showLabels
        H1_100Label := label.new(x=bar_index, y=ma1hr100, text="<----1hr SMA" + str.tostring(l5), xloc=xloc.bar_index, yloc=yloc.price, textcolor=labelcolour, style=label.style_label_left, color = color.rgb(1,1,1,100))

ma1hr300 = request.security(syminfo.tickerid, "60", ta.sma(close, l6))
plot(show_1hr300 and plot_1hr300 ? ma1hr300 : na, "1hr SMA300", color=#8a3af7c0, linewidth = 2)
var label H1_300Label = na
if barstate.islast
    if (not na(H1_300Label))
        label.delete(H1_300Label)
    if show_1hr300 and showLabels
        H1_300Label := label.new(x=bar_index, y=ma1hr300, text="<----1hr SMA" + str.tostring(l6), xloc=xloc.bar_index, yloc=yloc.price, textcolor=labelcolour, style=label.style_label_left, color = color.rgb(1,1,1,100))

//////////////////////////////////////////////////////////////////////
//                                                                  //
//                  TABLE CALCS                                     //
//                                                                  //
//////////////////////////////////////////////////////////////////////

string  tableYposInput = input.string("top", "Panel position", inline = "11", options = ["top", "middle", "bottom"])
string  tableXposInput = input.string("right", "", inline = "11", options = ["left", "center", "right"])
color   bullColorInput = input.color(color.new(color.green, 30), "Bull", inline = "12")
color   bearColorInput = input.color(color.new(color.red, 30), "Bear", inline = "12")
color   neutColorInput = input.color(color.new(color.gray, 30), "Neutral", inline = "12")

// Define conditions for other timeframes.
check5min = request.security(syminfo.tickerid, "1", close[5])
check15min = request.security(syminfo.tickerid, "1", close[15])
check30min = request.security(syminfo.tickerid, "1", close[30])
check1hour = request.security(syminfo.tickerid, "1", close[60])
check4hour = request.security(syminfo.tickerid, "1", close[240])
check1day = request.security(syminfo.tickerid, "1", close[1440])
checknow = open

is5minBullish = checknow > check5min
is15minBullish = checknow > check15min
is30minBullish = checknow > check30min
is1hourBullish = checknow > check1hour
is4hourBullish = checknow > check4hour
is1dayBullish = checknow > check1day

is5minBearish = checknow < check5min
is15minBearish = checknow < check15min
is30minBearish = checknow < check30min
is1hourBearish = checknow < check1hour
is4hourBearish = checknow < check4hour
is1dayBearish = checknow < check1day

// EMA lineup
[ema520t, ema550t, ema5200t] = request.security(syminfo.tickerid, "5", [ema1x, ema2x, ema3x])
[ema1520t, ema1550t, ema15200t] = request.security(syminfo.tickerid, "15", [ema1x, ema2x, ema3x])
[ema3020t, ema3050t, ema30200t] = request.security(syminfo.tickerid, "30", [ema1x, ema2x, ema3x])
[ema1h20t, ema1h50t, ema1h200t] = request.security(syminfo.tickerid, "60", [ema1x, ema2x, ema3x])
[ema4h20t, ema4h50t, ema4h200t] = request.security(syminfo.tickerid, "240", [ema1x, ema2x, ema3x])
[ema1d20t, ema1d50t, ema1d200t] = request.security(syminfo.tickerid, "D", [ema1x, ema2x, ema3x])

// 5-min timeframe
uptrend5t = ema520t > ema550t and ema550t > ema5200t
downtrend5t = ema520t < ema550t and ema550t < ema5200t

// 15-min timeframe
uptrend15t = ema1520t > ema1550t and ema1550t > ema15200t
downtrend15t = ema1520t < ema1550t and ema1550t < ema15200t

// 30-min timeframe
uptrend30t = ema3020t > ema3050t and ema3050t > ema30200t
downtrend30t = ema3020t < ema3050t and ema3050t < ema30200t

// 1-hour timeframe
uptrend1ht = ema1h20t > ema1h50t and ema1h50t > ema1h200t
downtrend1ht = ema1h20t < ema1h50t and ema1h50t < ema1h200t

// 4-hour timeframe
uptrend4ht = ema4h20t > ema4h50t and ema4h50t > ema4h200t
downtrend4ht = ema4h20t < ema4h50t and ema4h50t < ema4h200t

// 1-day timeframe
uptrend1dt = ema1d20t > ema1d50t and ema1d50t > ema1d200t
downtrend1dt = ema1d20t < ema1d50t and ema1d50t < ema1d200t

//Net Change
netChange5min = checknow - check5min
netChange15min = checknow - check15min
netChange30min = checknow - check30min
netChange1hour = checknow - check1hour
netChange4hour = checknow - check4hour
netChange1day = checknow - check1day

netChangePercentage5min = ((checknow - check5min) / check5min) * 100
netChangePercentage15min = ((checknow - check15min) / check15min) * 100
netChangePercentage30min = ((checknow - check30min) / check30min) * 100
netChangePercentage1hour = ((checknow - check1hour) / check1hour) * 100
netChangePercentage4hour = ((checknow - check4hour) / check4hour) * 100
netChangePercentage1day = ((checknow - check1day) / check1day) * 100

btcCheck5min = request.security(ticker.modify("BYBIT:BTCUSDT.P"),"1", close[5])
btcCheck15min = request.security(ticker.modify("BYBIT:BTCUSDT.P"),"1", close[15])
btcCheck30min = request.security(ticker.modify("BYBIT:BTCUSDT.P"),"1", close[30])
btcCheck1hour = request.security(ticker.modify("BYBIT:BTCUSDT.P"),"1", close[60])
btcCheck4hour = request.security(ticker.modify("BYBIT:BTCUSDT.P"),"1", close[240])
btcCheck1day = request.security(ticker.modify("BYBIT:BTCUSDT.P"),"1", close[1440])
btcCheckNow = request.security(ticker.modify("BYBIT:BTCUSDT.P"),"1", open)

btc5minBullish = btcCheckNow > btcCheck5min
btc15minBullish = btcCheckNow > btcCheck15min
btc30minBullish = btcCheckNow > btcCheck30min
btc1hourBullish = btcCheckNow > btcCheck1hour
btc4hourBullish = btcCheckNow > btcCheck4hour
btc1dayBullish = btcCheckNow > btcCheck1day

btc5minBearish = btcCheckNow < btcCheck5min
btc15minBearish = btcCheckNow < btcCheck15min
btc30minBearish = btcCheckNow < btcCheck30min
btc1hourBearish = btcCheckNow < btcCheck1hour
btc4hourBearish = btcCheckNow < btcCheck4hour
btc1dayBearish = btcCheckNow < btcCheck1day

// BTC EMA lineup
[ema520, ema550, ema5200] = request.security(ticker.modify("BYBIT:BTCUSDT.P"), "5", [ema1x, ema2x, ema3x])
[ema1520, ema1550, ema15200] = request.security(ticker.modify("BYBIT:BTCUSDT.P"), "15", [ema1x, ema2x, ema3x])
[ema3020, ema3050, ema30200] = request.security(ticker.modify("BYBIT:BTCUSDT.P"), "30", [ema1x, ema2x, ema3x])
[ema1h20, ema1h50, ema1h200] = request.security(ticker.modify("BYBIT:BTCUSDT.P"), "60", [ema1x, ema2x, ema3x])
[ema4h20, ema4h50, ema4h200] = request.security(ticker.modify("BYBIT:BTCUSDT.P"), "240", [ema1x, ema2x, ema3x])
[ema1d20, ema1d50, ema1d200] = request.security(ticker.modify("BYBIT:BTCUSDT.P"), "D", [ema1x, ema2x, ema3x])

// 5-min timeframe
btcuptrend5 = ema520 > ema550 and ema550 > ema5200
btcdowntrend5 = ema520 < ema550 and ema550 < ema5200

// 15-min timeframe
btcuptrend15 = ema1520 > ema1550 and ema1550 > ema15200
btcdowntrend15 = ema1520 < ema1550 and ema1550 < ema15200

// 30-min timeframe
btcuptrend30 = ema3020 > ema3050 and ema3050 > ema30200
btcdowntrend30 = ema3020 < ema3050 and ema3050 < ema30200

// 1-hour timeframe
btcuptrend1h = ema1h20 > ema1h50 and ema1h50 > ema1h200
btcdowntrend1h = ema1h20 < ema1h50 and ema1h50 < ema1h200

// 4-hour timeframe
btcuptrend4h = ema4h20 > ema4h50 and ema4h50 > ema4h200
btcdowntrend4h = ema4h20 < ema4h50 and ema4h50 < ema4h200

// 1-day timeframe
btcuptrend1d = ema1d20 > ema1d50 and ema1d50 > ema1d200
btcdowntrend1d = ema1d20 < ema1d50 and ema1d50 < ema1d200

// ------------------------------------
// ---------------Table----------------
// ------------------------------------

// Table creation and settings
//Background vars
var color cell_up = color.green
var color cell_dn = color.red
var color cell_neutral = color.gray
var int cell_transp = 45

btctrendStatus5 = if btcuptrend5
    "Uptrend"
else
    if btcdowntrend5
        "Downtrend"
    else
        "Sideways"

btctrendStatus15 = if btcuptrend15
    "Uptrend"
else
    if btcdowntrend15
        "Downtrend"
    else
        "Sideways"

btctrendStatus30 = if btcuptrend30
    "Uptrend"
else
    if btcdowntrend30
        "Downtrend"
    else
        "Sideways"

btctrendStatus1h = if btcuptrend1h
    "Uptrend"
else
    if btcdowntrend1h
        "Downtrend"
    else
        "Sideways"

btctrendStatus4h = if btcuptrend4h
    "Uptrend"
else
    if btcdowntrend4h
        "Downtrend"
    else
        "Sideways"

btctrendStatus1d = if btcuptrend1d
    "Uptrend"
else
    if btcdowntrend1d
        "Downtrend"
    else
        "Sideways"


trendStatus5 = if uptrend5t
    "Uptrend"
else
    if downtrend5t
        "Downtrend"
    else
        "Sideways"

trendStatus15 = if uptrend15t
    "Uptrend"
else
    if downtrend15t
        "Downtrend"
    else
        "Sideways"

trendStatus30 = if uptrend30t
    "Uptrend"
else
    if downtrend30t
        "Downtrend"
    else
        "Sideways"

trendStatus1h = if uptrend1ht
    "Uptrend"
else
    if downtrend1ht
        "Downtrend"
    else
        "Sideways"

trendStatus4h = if uptrend4ht
    "Uptrend"
else
    if downtrend4ht
        "Downtrend"
    else
        "Sideways"

trendStatus1d = if uptrend1dt
    "Uptrend"
else
    if downtrend1dt
        "Downtrend"
    else
        "Sideways"

// Table creation and settings.
var table tableId = table.new(tableYposInput + "_" + tableXposInput, 6, 8, bgcolor = color.rgb(0, 8, 11, 77), frame_color = color.green, frame_width = 1, border_color = color.white, border_width = 1)
var string is5minStatus = na
var string is15minStatus = na
var string is30minStatus = na
var string is1hourStatus = na
var string is4hourStatus = na
var string is1dayStatus = na
var string btc5minStatus = na
var string btc15minStatus = na
var string btc30minStatus = na
var string btc1hourStatus = na
var string btc4hourStatus = na
var string btc1dayStatus = na

if barstate.islast

//BTC.
    btc5minStatus := if btc5minBullish
        "Bullish"
    else
        "Bearish"

    btc15minStatus := if btc15minBullish
        "Bullish"
    else
        "Bearish"

    btc30minStatus := if btc30minBullish
        "Bullish"
    else
        "Bearish"

    btc1hourStatus := if btc1hourBullish
        "Bullish"
    else
        "Bearish"

    btc4hourStatus := if btc4hourBullish
        "Bullish"
    else
        "Bearish"

    btc1dayStatus := if btc1dayBullish
        "Bullish"
    else
        "Bearish"

    is5minStatus := if is5minBullish
        "Bullish"
    else
        "Bearish"

    is15minStatus := if is15minBullish
        "Bullish"
    else
        "Bearish"

    is30minStatus := if is30minBullish
        "Bullish"
    else
        "Bearish"

    is1hourStatus := if is1hourBullish
        "Bullish"
    else
        "Bearish"

    is4hourStatus := if is4hourBullish
        "Bullish"
    else
        "Bearish"

    is1dayStatus := if is1dayBullish
        "Bullish"
    else
        "Bearish"

if barstate.islast and showTable
    table.cell(tableId, 0, 0, "EMA Line-Up", text_size = size.small, text_color = color.white)
    table.cell(tableId, 1, 0, str.tostring(trendStatus), bgcolor=color.new(trendStatus == "Uptrend" ? cell_up : trendStatus == "Downtrend" ? cell_dn : cell_neutral, cell_transp), text_size = size.small, text_color = color.white)    
    table.cell(tableId, 5, 0, "BTC Trend", text_size = size.small, text_color = color.white)

    table.cell(tableId, 0, 1, "5 minute", text_size = size.small, text_color = color.white)
    table.cell(tableId, 1, 1, str.tostring(trendStatus5), bgcolor=color.new(trendStatus5 == "Uptrend" ? cell_up : trendStatus5 == "Downtrend" ? cell_dn : cell_neutral, cell_transp), text_size = size.small, text_color = color.white)    
    table.cell(tableId, 5, 1, str.tostring(btctrendStatus5), bgcolor=color.new(btctrendStatus5 == "Uptrend" ? cell_up : btctrendStatus5 == "Downtrend" ? cell_dn : cell_neutral, cell_transp), text_size = size.small, text_color = color.white)    

    table.cell(tableId, 0, 2, "15 minute", text_size = size.small, text_color = color.white)
    table.cell(tableId, 1, 2, str.tostring(trendStatus15), bgcolor=color.new(trendStatus15 == "Uptrend" ? cell_up : trendStatus15 == "Downtrend" ? cell_dn : cell_neutral, cell_transp), text_size = size.small, text_color = color.white)    
    table.cell(tableId, 5, 2, str.tostring(btctrendStatus15), bgcolor=color.new(btctrendStatus15 == "Uptrend" ? cell_up : btctrendStatus15 == "Downtrend" ? cell_dn : cell_neutral, cell_transp), text_size = size.small, text_color = color.white)    
    
    table.cell(tableId, 0, 3, "30 minute", text_size = size.small, text_color = color.white)
    table.cell(tableId, 1, 3, str.tostring(trendStatus30), bgcolor=color.new(trendStatus30 == "Uptrend" ? cell_up : trendStatus30 == "Downtrend" ? cell_dn : cell_neutral, cell_transp), text_size = size.small, text_color = color.white)    
    table.cell(tableId, 5, 3, str.tostring(btctrendStatus30), bgcolor=color.new(btctrendStatus30 == "Uptrend" ? cell_up : btctrendStatus30 == "Downtrend" ? cell_dn : cell_neutral, cell_transp), text_size = size.small, text_color = color.white)    
    
    table.cell(tableId, 0, 4, "1 hour", text_size = size.small, text_color = color.white)
    table.cell(tableId, 1, 4, str.tostring(trendStatus1h), bgcolor=color.new(trendStatus1h == "Uptrend" ? cell_up : trendStatus1h == "Downtrend" ? cell_dn : cell_neutral, cell_transp), text_size = size.small, text_color = color.white)    
    table.cell(tableId, 5, 4, str.tostring(btctrendStatus1h), bgcolor=color.new(btctrendStatus1h == "Uptrend" ? cell_up : btctrendStatus1h == "Downtrend" ? cell_dn : cell_neutral, cell_transp), text_size = size.small, text_color = color.white)    
    
    table.cell(tableId, 0, 5, "4 hour", text_size = size.small, text_color = color.white)
    table.cell(tableId, 1, 5, str.tostring(trendStatus4h), bgcolor=color.new(trendStatus4h == "Uptrend" ? cell_up : trendStatus4h == "Downtrend" ? cell_dn : cell_neutral, cell_transp), text_size = size.small, text_color = color.small, text_color = color.white)    
    table.cell(tableId, 5, 5, str.tostring(btctrendStatus4h), bgcolor=color.new(btctrendStatus4h == "Uptrend" ? cell_up : btctrendStatus4h == "Downtrend" ? cell_dn : cell_neutral, cell_transp), text_size = size.small, text_color = color.white)    
    
    table.cell(tableId, 0, 6, "1 day", text_size = size.small, text_color = color.white)
    table.cell(tableId, 1, 6, str.tostring(trendStatus1d), bgcolor=color.new(trendStatus1d == "Uptrend" ? cell_up : trendStatus1d == "Downtrend" ? cell_dn : cell_neutral, cell_transp), text_size = size.small, text_color = color.white)    
    table.cell(tableId, 5, 6, str.tostring(btctrendStatus1d), bgcolor=color.new(btctrendStatus1d == "Uptrend" ? cell_up : btctrendStatus1d == "Downtrend" ? cell_dn : cell_neutral, cell_transp), text_size = size.small, text_color = color.white)    

//Alerts

// Check if all timeframes are aligned in either uptrend or downtrend
allUptrend = uptrend5t and uptrend15t and uptrend30t and uptrend1ht and uptrend4ht and uptrend1dt
allDowntrend = downtrend5t and downtrend15t and downtrend30t and downtrend1ht and downtrend4ht and downtrend1dt

var bool alertTriggered = false // Variable to track if the alert has been triggered

// Alerts
if allUptrend and not alertTriggered
    alert(message="All Timeframes Aligned in Uptrend", freq=alert.freq_once_per_bar_close)
    alertTriggered := true // Set the trigger flag to true

if allDowntrend and not alertTriggered
    alert(message="All Timeframes Aligned in Downtrend", freq=alert.freq_once_per_bar_close)
    alertTriggered := true // Set the trigger flag to true

// Reset the trigger flag if the condition no longer holds true
if not allUptrend and not allDowntrend
    alertTriggered := false

